batch_size: 256
buffer_params:
  goal_selection_strategy: future
  n_sampled_goal: 4
  online_sampling: true
buffer_size: 1000000
gamma: 0.99
learning_rate: 0.001
learning_starts: 1000
policy_params:
  n_critics: 2
  net_arch:
  - 512
  - 512
  - 512
target_noise_clip: 0.5
target_policy_noise: 0.2
tau: 0.005
